const {test}=require('node:test');const assert=require('node:assert/strict');const crypto=require('node:crypto');
const {initialState,applyEvent,evaluate,standing,incidentCount,view}=require('../dist/app/modules/community/policy');
const keys=Object.fromEntries(['governor','a','b','c','d'].map(id=>[id,crypto.generateKeyPairSync('ed25519')]));
const pub=id=>keys[id].publicKey.export({type:'spki',format:'pem'}).toString();let seq=0;const now=2000000000;
function event(s,actor,body,at=now){const payload=JSON.stringify({id:'e'+(++seq),actor,...body});const signature=crypto.sign(null,Buffer.from('TrustSECO-community-v1\n'+payload),keys[actor].privateKey).toString('base64');return applyEvent(s,payload,signature,at)}
function setup(){let s=initialState(pub('governor'));for(const id of ['a','b','c','d'])s=event(s,'governor',{kind:'enrol',member:id,key:pub(id),operator:id,githubId:id,accountCreatedAt:now-200*86400,evidence:'operator attestation'});return s}
function open(s,id='r',at=now){return event(s,'governor',{kind:'open',round:id,package:'demo/package',metric:'github_stars',source:'GitHub',method:'v1',duration:10},at)}
function observe(s,id,value,r='r',at=now){return event(s,id,{kind:'observe',round:r,value,source:'GitHub',method:'v1',observedAt:at},at)}
function result(s){return evaluate(s.rounds[0],s)}
function incident(s,number,cause='cause'+number){const at=now+number*20;const round='r'+number;s=open(s,round,at);s=observe(s,'d',900,round,at);s=event(s,'governor',{kind:'close',round},at+11);return event(s,'governor',{kind:'substantiate',round,observation:s.rounds.find(r=>r.id===round).observations[0].id,cause,evidence:'reproducible fixture '+number,reason:'Fixture expected 100, collector returned 900'},at+12)}
test('one observation cannot verify a finding',()=>assert.equal(result(observe(open(setup()),'a',900)).status,'pending'));
test('three compatible values verify; outlier preserved without automatic incident',()=>{let s=open(setup());for(const [id,v] of [['a',900],['b',910],['c',905],['d',100]])s=observe(s,id,v);assert.equal(result(s).status,'verified');assert.equal(result(s).conflicts.length,1);assert.equal(s.incidents.length,0)});
test('100,102,900 is disputed',()=>{let s=open(setup());for(const [id,v] of [['a',100],['b',102],['c',900]])s=observe(s,id,v);assert.equal(result(s).status,'disputed')});
test('pairwise chaining does not manufacture agreement',()=>{let s=open(setup());for(const [id,v] of [['a',900],['b',918],['c',936]])s=observe(s,id,v);assert.equal(result(s).status,'disputed')});
test('duplicate contributor cannot vote twice',()=>assert.throws(()=>observe(observe(open(setup()),'a',900),'a',900),/already observed/));
test('late and future observations rejected',()=>{const s=open(setup());assert.throws(()=>observe(s,'a',900,'r',now+20),/closed/);assert.throws(()=>event(s,'a',{kind:'observe',round:'r',value:900,source:'GitHub',method:'v1',observedAt:now+1}),/future/)});
test('new round allows changed values',()=>{let s=observe(open(setup()),'a',900);s=open(s,'later',now+2*86400);s=observe(s,'a',1000,'later',now+2*86400);assert.equal(s.rounds[1].observations[0].value,1000)});
test('bad signatures, replay and unauthorised review rejected',()=>{const s=setup();assert.throws(()=>applyEvent(s,JSON.stringify({id:'x',actor:'a',kind:'open'}),'bad',now));const a=s.audit[0];assert.throws(()=>applyEvent(s,a.payload,a.signature,now),/Duplicate/);assert.throws(()=>event(s,'a',{kind:'reinstate',member:'d',reason:'x'}),/authority/)});
test('enrolment age and duplicate operator checked',()=>{const s=setup();assert.throws(()=>event(s,'governor',{kind:'enrol',member:'z',key:pub('a'),operator:'z',githubId:'z',accountCreatedAt:now,evidence:'x'}),/180/);assert.throws(()=>event(s,'governor',{kind:'enrol',member:'z',key:pub('a'),operator:'a',githubId:'z',accountCreatedAt:now-200*86400,evidence:'x'}),/already/)});
test('3 substantiated incidents flag; 5 suspend; suspension survives ageing',()=>{let s=setup();for(let i=1;i<=5;i++){s=incident(s,i);assert.equal(standing(s,'d',now+i*20+12),i<3?'active':i<5?'review':'suspended')}assert.equal(standing(s,'d',now+90*86400),'suspended');s=open(s,'post',now+200);s=observe(s,'d',900,'post',now+200);assert.equal(s.rounds.at(-1).observations[0].eligible,false)});
test('one collector failure is not five strikes',()=>{let s=setup();for(let i=1;i<=5;i++)s=incident(s,i,'same-bug');assert.equal(incidentCount(s,'d',now+200),1);assert.equal(standing(s,'d',now+200),'active')});
test('appeal, overturn and explicit reinstatement preserve history',()=>{let s=setup();for(let i=1;i<=5;i++)s=incident(s,i);s=event(s,'d',{kind:'appeal',incident:s.incidents[0].id,reason:'time mismatch'},now+200);s=event(s,'governor',{kind:'overturn',incident:s.incidents[0].id,reason:'appeal substantiated'},now+201);assert.equal(standing(s,'d',now+201),'suspended');s=event(s,'governor',{kind:'reinstate',member:'d',reason:'review completed'},now+202);assert.equal(standing(s,'d',now+202),'active');assert.equal(s.incidents.length,5)});
test('replaying signed audit events yields identical state',()=>{let s=setup();s=incident(s,1);let replica=initialState(pub('governor'));for(const e of s.audit)replica=applyEvent(replica,e.payload,e.signature,e.at,e.height);assert.deepEqual(replica,s)});
test('unverified or suspended observations do not earn prototype credits',()=>{let s=setup();for(let i=1;i<=5;i++)s=incident(s,i);s=open(s,'credit',now+200);for(const id of ['a','b','c','d'])s=observe(s,id,100,'credit',now+200);s=event(s,'governor',{kind:'close',round:'credit'},now+211);assert.equal(view(s,now+211).members.find(m=>m.id==='a').rewardEligibleObservations,1);assert.equal(view(s,now+211).members.find(m=>m.id==='d').rewardEligibleObservations,0)});
